name: Python package

on:
  push:
    branches:
      - main

jobs:
  build:
    env:
      PYTHONIOENCODING: utf-8
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: pyinstaller -F -n dlctool main.py

      - name: Package application (MacOS)
        if: runner.os == 'macOS'
        run: |
          curl https://github.com/dnasdw/3dstool/releases/download/v1.2.6/3dstool_macos_x86_64.tar.gz -o 3dstool.tar.gz
          gzip -d 3dstool.tar.gz
          cd dist
          tar -xf ../3dstool.tar

      - name: Package application (Windows)
        if: runner.os == 'Windows'
        run: |
          curl https://github.com/dnasdw/3dstool/releases/download/v1.2.6/3dstool.zip -o 3dstool.zip
          cd dist
          unzip ../3dstool.zip
        shell: bash
     
      - name: Package application (Linux)
        if: runner.os == 'Linux'
        run: |
          curl https://github.com/dnasdw/3dstool/releases/download/v1.2.6/3dstool_linux_x86_64.tar.gz -o 3dstool.tar.gz
          gzip -d 3dstool.tar.gz
          cd dist
          tar -xf ../3dstool.tar

      - uses: actions/upload-artifact@v2
        with:
          name: dlctool-${{ runner.os }}
          path: dist